### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) 

### ISSUE THREAD

**Issue by duzhipeng** [qcloudsms/qcloudsms_py#1]
如果可以的话，建议Https的请求用Requests，别用自带的那个包了，不然总是出类似的问题。

毕竟腾讯云的官方包现在都利用Requests作请求了。

**Comment by qcloudsms** [comment]
您好，这个错误是证书验证失败，跟本地测试有关，与是否使用 `requests` 是无关的，这里不使用 `requests` 是为了保持包的简洁性，也考虑到有些用户没有使用 `pip`。

**Comment by duzhipeng** [comment]
> 您好，这个错误是证书验证失败，跟本地测试有关，与是否使用 requests 是无关的，这里不使用 requests 是为了保持包的简洁性，也该考虑到有些用户没有使用 pip。

明白，其实我的言下之意是用requests的话，非常方便的可以关闭验证解决这个问题以便于调试，如果用自带的包还需要一些设置，比如不好的全局设置。
总的而言，我觉得您说的也在理，所以就当我一个意见好了，这个工单关闭吧 :)
